---
version: "3.7"
services:
  redis:
     image: redis:latest
     hostname: redis
     ports:
     - target: 6379
       published: 6379
       protocol: tcp
     volumes:
     - redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
     entrypoint: redis-server --appendonly yes
volumes:
  redis-data:
